CREATE TABLE dbo.employee (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    gender VARCHAR(10),
    department VARCHAR(100),
    date_of_joining DATE,
    salary NUMERIC(10, 2)
);
